version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      
      - .:/usr/src/app
      
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    command: npm run dev
