version: "3.8"

services:
  frontend:
    image: <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/multisync-frontend:staging
    restart: always
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:4000
    ports:
      - "80:3000"
