version: "3.8"

services:
  frontend:
    image: 506175605104.dkr.ecr.ap-southeast-2.amazonaws.com/multisync-frontend:staging
    restart: always
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:4000
    ports:
      - "80:3000"
