# frontend/Dockerfile.dev

FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN chmod +x node_modules/.bin/next  # ✅ Make next executable

EXPOSE 3000

CMD ["npm", "run", "dev"]
